---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: GitHub’s official command line tool
app_name: gh
app_repo: https://github.com/cli/cli
app_type: standalone
app_website: https://cli.github.com
archive_conf_path: gh_{version}_{os}_{arch}
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/cli/cli/releases/download/v{version}/gh_{version}_checksums.txt
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/cli/cli/releases/download/v{version}/gh_{version}_{os}_{arch}.{ext}
gpg_enabled: false
install_map_enabled: false
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-gh
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-gh.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv5
    armv6*: armv6
    armv7*: armv7
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
sys_ext_default: tar.gz
sys_ext_enabled: true
sys_ext_yaml:
    macOS-*: zip
sys_os_enabled: true
sys_os_yaml:
    darwin: macOS
    linux: linux
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
